# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbrVyyoPTBIGsIFhU-JF5x5qPczubPun
"""

import torch
print("GPU Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("Device Name:", torch.cuda.get_device_name(0))

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Unzip all datasets from Google Drive into separate folders
!mkdir -p ./data_two_wheeler && unzip -o -q "/content/drive/MyDrive/Two Wheeler.zip" -d ./data_two_wheeler
!mkdir -p ./data_vehicle && unzip -o -q "/content/drive/MyDrive/Vehicle.zip" -d ./data_vehicle
!mkdir -p ./data_bicycle && unzip -o -q "/content/drive/MyDrive/bicycle.zip" -d ./data_bicycle
!mkdir -p ./data_cone && unzip -o -q "/content/drive/MyDrive/cone.zip" -d ./data_cone
!mkdir -p ./data_cow && unzip -o -q "/content/drive/MyDrive/cow.zip" -d ./data_cow
!mkdir -p ./data_green && unzip -o -q "/content/drive/MyDrive/green.zip" -d ./data_green
!mkdir -p ./data_obstacle && unzip -o -q "/content/drive/MyDrive/obstacle.zip" -d ./data_obstacle
!mkdir -p ./data_pedestrian && unzip -o -q "/content/drive/MyDrive/pedestrain det.zip" -d ./data_pedestrian
!mkdir -p ./data_red && unzip -o -q "/content/drive/MyDrive/red light.zip" -d ./data_red
!mkdir -p ./data_sign10 && unzip -o -q "/content/drive/MyDrive/sign10.zip" -d ./data_sign10
!mkdir -p ./data_sign30 && unzip -o -q "/content/drive/MyDrive/sign30.zip" -d ./data_sign30
!mkdir -p ./data_traffic_sign && unzip -o -q "/content/drive/MyDrive/traffic sign.zip" -d ./data_traffic_sign
!mkdir -p ./data_yellow && unzip -o -q "/content/drive/MyDrive/yellow.zip" -d ./data_yellow

#optimised usage of the gpu
import torch
import gc

gc.collect()
torch.cuda.empty_cache()

# Create extraction folders and unzip each dataset from Google Drive
!mkdir -p ./data_two_wheeler && unzip -o -q "/content/drive/MyDrive/Two Wheeler.zip" -d ./data_two_wheeler
!mkdir -p ./data_vehicle && unzip -o -q "/content/drive/MyDrive/Vehicle.zip" -d ./data_vehicle
!mkdir -p ./data_bicycle && unzip -o -q "/content/drive/MyDrive/bicycle.zip" -d ./data_bicycle
!mkdir -p ./data_cone && unzip -o -q "/content/drive/MyDrive/cone.zip" -d ./data_cone
!mkdir -p ./data_cow && unzip -o -q "/content/drive/MyDrive/cow.zip" -d ./data_cow
!mkdir -p ./data_green && unzip -o -q "/content/drive/MyDrive/green.zip" -d ./data_green
!mkdir -p ./data_obstacle && unzip -o -q "/content/drive/MyDrive/obstacle.zip" -d ./data_obstacle
!mkdir -p ./data_pedestrian && unzip -o -q "/content/drive/MyDrive/pedestrain det.zip" -d ./data_pedestrian
!mkdir -p ./data_red && unzip -o -q "/content/drive/MyDrive/red light.zip" -d ./data_red
!mkdir -p ./data_sign10 && unzip -o -q "/content/drive/MyDrive/sign10.zip" -d ./data_sign10
!mkdir -p ./data_sign30 && unzip -o -q "/content/drive/MyDrive/sign30.zip" -d ./data_sign30
!mkdir -p ./data_traffic && unzip -o -q "/content/drive/MyDrive/traffic sign.zip" -d ./data_traffic
!mkdir -p ./data_yellow && unzip -o -q "/content/drive/MyDrive/yellow.zip" -d ./data_yellow

print("All 13 datasets unzipped successfully!")

# 2. Update DATA_FOLDERS list and build combined_data.yaml
import os
import glob
import yaml

DATA_FOLDERS = [
    "./data_two_wheeler",
    "./data_vehicle",
    "./data_bicycle",
    "./data_cone",
    "./data_cow",
    "./data_green",
    "./data_obstacle",
    "./data_pedestrian",
    "./data_red",
    "./data_sign10",
    "./data_sign30",
    "./data_traffic",
    "./data_yellow"
]

# Scan for all unique class IDs across all 13 dataset folders
found_class_ids = set()
for folder in DATA_FOLDERS:
    txt_files = glob.glob(os.path.join(folder, "**/*.txt"), recursive=True)
    for path in txt_files:
        if "data.yaml" in path or "README" in path:
            continue
        with open(path, "r") as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) > 0 and parts[0].isdigit():
                    found_class_ids.add(int(parts[0]))

sorted_ids = sorted(list(found_class_ids))
print(f"Detected Class IDs across all 13 datasets: {sorted_ids}")

# Build mapping dictionary for class names
class_names = {cid: f"Class_{cid}" for cid in sorted_ids}

# Create test_data.yaml configured for training
yaml_content = {
    'path': '/content',
    'train': DATA_FOLDERS,
    'val': DATA_FOLDERS,
    'names': class_names
}

with open("test_data.yaml", "w") as f:
    yaml.dump(yaml_content, f)

print("\n`test_data.yaml` successfully updated with all 13 folders!")

#Remap Labels and Generate combined_data.yaml
import os
import glob
import yaml

# Directories created from your unzipped files
DATA_FOLDERS = [
    "./data_cow",
    "./data_green",
    "./data_pedestrian",
    "./data_red",
    "./data_yellow"
]

# 1. Scan for all unique class IDs existing across your unzipped text files
found_class_ids = set()

for folder in DATA_FOLDERS:
    txt_files = glob.glob(os.path.join(folder, "**/*.txt"), recursive=True)
    for path in txt_files:
        if "data.yaml" in path or "README" in path:
            continue
        with open(path, "r") as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) > 0 and parts[0].isdigit():
                    found_class_ids.add(int(parts[0]))

sorted_ids = sorted(list(found_class_ids))
print(f"Detected Class IDs in uploaded files: {sorted_ids}")

# 2. Build names dictionary using detected class IDs
# (You can rename these string labels if needed)
class_names = {cid: f"Class_{cid}" for cid in sorted_ids}

# 3. Write test_data.yaml pointing to existing folders
yaml_content = {
    'path': '/content',
    'train': DATA_FOLDERS,
    'val': DATA_FOLDERS,
    'names': class_names
}

with open("test_data.yaml", "w") as f:
    yaml.dump(yaml_content, f)

print("\n`test_data.yaml` successfully created!")
print("YAML Class Mapping:", class_names)

#hardware detection gpu presence /model loading yolo11s/test train /model export yolo to onnx
!pip install -q ultralytics

import torch
from ultralytics import YOLO

# Auto-detect whether GPU is available, otherwise fall back to CPU
device_to_use = 0 if torch.cuda.is_available() else 'cpu'

# Load base model
model = YOLO("yolo11s.pt")

# Train test run
model.train(
    data="test_data.yaml",
    epochs=10,
    imgsz=640,
    batch=16,
    device=device_to_use
)

# Export test ONNX file
onnx_path = model.export(format="onnx", dynamic=False)
print(f"Test training complete! ONNX file exported at: {onnx_path}")

import os
import glob
import yaml

# List of all extracted dataset directories (matching your unzipped folder names)
DATA_FOLDERS = [
    "./data_cone", "./data_obstacle", "./data_cow",
    "./data_pedestrian", "./data_bicycle", "./data_red",
    "./data_green", "./data_yellow", "./data_two_wheeler",
    "./data_sign10", "./data_traffic", "./data_sign30",
    "./data_vehicle"
]

# Map single-class folders to unified Class IDs (0 to 12)
FOLDER_CLASS_MAP = {
    "./data_cone": 0,          # Cone
    "./data_obstacle": 1,      # Traffic Barrier / Obstacle
    "./data_cow": 2,           # Cow
    "./data_pedestrian": 3,    # Pedestrian
    "./data_bicycle": 4,       # Bicyclist
    "./data_red": 5,           # Red Traffic Light
    "./data_green": 6,         # Green Traffic Light
    "./data_yellow": 7,        # Orange/Yellow Traffic Light
    "./data_two_wheeler": 8,   # Two-Wheeler
    "./data_sign10": 9,        # Speed Limit Sign 10
    "./data_traffic": 10,      # Speed Limit Sign 15 / Traffic Sign
    "./data_sign30": 11,       # Speed Limit Sign 30
    "./data_vehicle": 12       # Cars/Vehicle
}

# Define human-readable class names
CLASS_NAMES = {
    0: "Cone",
    1: "Obstacle",
    2: "Cow",
    3: "Pedestrian",
    4: "Bicycle",
    5: "Red Light",
    6: "Green Light",
    7: "Yellow Light",
    8: "Two Wheeler",
    9: "Sign 10",
    10: "Traffic Sign",
    11: "Sign 30",
    12: "Vehicle"
}

# Create test_data.yaml configured with 13 unified classes
yaml_content = {
    'path': '/content',
    'train': DATA_FOLDERS,
    'val': DATA_FOLDERS,
    'names': CLASS_NAMES
}

with open("test_data.yaml", "w") as f:
    yaml.dump(yaml_content, f)

print("test_data.yaml successfully updated with 13 unified classes!")

import os
import glob
import yaml

# List of extracted dataset directories in your Colab environment
DATA_FOLDERS = [
    "./data_cone", "./data_obstacle", "./data_cow",
    "./data_pedestrian", "./data_bicycle", "./data_red",
    "./data_green", "./data_yellow", "./data_two_wheeler",
    "./data_sign10", "./data_traffic", "./data_sign30",
    "./data_vehicle"
]

# Map single-class folders to unified Class IDs (0 to 12)
FOLDER_CLASS_MAP = {
    "./data_cone": 0,          # Cone
    "./data_obstacle": 1,      # Traffic Barrier / Obstacle
    "./data_cow": 2,           # Cow
    "./data_pedestrian": 3,    # Pedestrian
    "./data_bicycle": 4,       # Bicyclist
    "./data_red": 5,           # Red Traffic Light
    "./data_green": 6,         # Green Traffic Light
    "./data_yellow": 7,        # Orange/Yellow Traffic Light
    "./data_two_wheeler": 8,   # Two-Wheeler
    "./data_sign10": 9,        # Speed Limit Sign 10
    "./data_traffic": 10,      # Speed Limit Sign 15 / Traffic Sign
    "./data_sign30": 11,       # Speed Limit Sign 30
    "./data_vehicle": 12       # Cars/Vehicle
}

# 1. Update text label files across all folders
for folder, target_id in FOLDER_CLASS_MAP.items():
    txt_files = glob.glob(os.path.join(folder, "**/*.txt"), recursive=True)
    for path in txt_files:
        if "data.yaml" in path or "README" in path:
            continue
        with open(path, "r") as f:
            lines = f.readlines()
        new_lines = []
        for line in lines:
            parts = line.strip().split()
            if len(parts) > 0:
                parts[0] = str(target_id)
                new_lines.append(" ".join(parts))
        with open(path, "w") as f:
            f.write("\n".join(new_lines) + "\n")

# 2. Write combined_data.yaml
yaml_content = {
    'path': '/content',
    'train': DATA_FOLDERS,
    'val': DATA_FOLDERS,
    'names': {
        0: 'Cone',
        1: 'Traffic Barrier',
        2: 'Cow',
        3: 'Pedestrian',
        4: 'Bicyclist',
        5: 'Red Traffic Light',
        6: 'Green Traffic Light',
        7: 'Orange Traffic Light',
        8: 'Two-Wheeler',
        9: 'Speed Limit Sign 10',
        10: 'Speed Limit Sign 15',
        11: 'Speed Limit Sign 30',
        12: 'Cars'
    }
}

with open("combined_data.yaml", "w") as f:
    yaml.dump(yaml_content, f)

print("Label remapping complete! combined_data.yaml successfully generated.")

import torch
from ultralytics import YOLO

device_to_use = 0 if torch.cuda.is_available() else 'cpu'

# Load base model
model = YOLO("yolo11s.pt")

# Train on the newly remapped combined_data.yaml
model.train(
    data="combined_data.yaml",
    epochs=10,
    imgsz=640,
    batch=16,
    device=device_to_use
)

# Export trained model to ONNX
onnx_path = model.export(format="onnx", dynamic=False)
print(f"Training complete! ONNX file exported at: {onnx_path}")

#save trained model
!cp /content/runs/detect/train/weights/best.pt "/content/drive/MyDrive/yolo11s_best.pt"
print("Model saved to Google Drive!")

import glob
from ultralytics import YOLO
from IPython.display import Image, display

# 1. Load trained model directly from Google Drive
model = YOLO("/content/drive/MyDrive/yolo11s_best.pt")

# 2. Run detection pointing to the actual images subfolder
results = model.predict(source="/content/data_vehicle/train/images", save=True, conf=0.25)
print("Inference finished! Saved to /content/runs/detect/predict")

# 3. Automatically display the first detected output image
output_images = glob.glob("/content/runs/detect/predict/*.jpg")
if output_images:
    display(Image(filename=output_images[0]))

import glob
from ultralytics import YOLO
from IPython.display import Image, display

# 1. Load your saved model from Drive
model = YOLO("/content/drive/MyDrive/yolo11s_best.pt")

# 2. Pick the first image from your dataset
sample_images = glob.glob("/content/data_vehicle/train/images/*.jpg")

if sample_images:
    # Run detection on just 1 image
    results = model.predict(source=sample_images[0], save=True, conf=0.25)

    # Display the prediction output
    output_images = glob.glob("/content/runs/detect/predict*/*.jpg")
    if output_images:
        display(Image(filename=output_images[-1]))

#train (70%), Validation (20%), and Test (10%)
import os
import glob
import shutil
from sklearn.model_selection import train_test_split

# 1. Gather all matching image and label pairs from /content
all_images = []
for ext in ("*.jpg", "*.jpeg", "*.png", "*.JPG", "*.JPEG", "*.PNG"):
    all_images.extend(glob.glob("/content/**/" + ext, recursive=True))

# Exclude existing yolo_dataset or checkpoint folders
all_images = [img for img in all_images if ".ipynb_checkpoints" not in img and "yolo_dataset" not in img]

image_label_pairs = []

for img in all_images:
    txt_path = os.path.splitext(img)[0] + ".txt"
    if not os.path.exists(txt_path):
        alt_txt_path = img.replace("/images/", "/labels/")
        alt_txt_path = os.path.splitext(alt_txt_path)[0] + ".txt"
        if os.path.exists(alt_txt_path):
            txt_path = alt_txt_path

    if os.path.exists(txt_path):
        try:
            with open(txt_path, "r") as f:
                first_line = f.readline().strip().split()
                if first_line:
                    primary_cls = int(float(first_line[0]))
                    image_label_pairs.append((img, txt_path, primary_cls))
        except (ValueError, IndexError):
            continue

if not image_label_pairs:
    raise RuntimeError("No matching image-label pairs found!")

print(f"Total matched image-label pairs found: {len(image_label_pairs)}")

# 2. Perform Random Split: 70% Train, 20% Val, 10% Test (stratify=None avoids single-member class errors)
X_paths = [(p[0], p[1]) for p in image_label_pairs]

# Split off 10% test set
X_train_val, X_test = train_test_split(
    X_paths, test_size=0.10, random_state=42
)

# Split remaining 90% into 70% train and 20% validation
X_train, X_val = train_test_split(
    X_train_val, test_size=0.2222, random_state=42
)

# 3. Build YOLO Directory Structure
dataset_base = "/content/yolo_dataset"

for split in ["train", "val", "test"]:
    os.makedirs(os.path.join(dataset_base, f"images/{split}"), exist_ok=True)
    os.makedirs(os.path.join(dataset_base, f"labels/{split}"), exist_ok=True)

def copy_files(split_data, split_type):
    for img_path, txt_path in split_data:
        shutil.copy(img_path, os.path.join(dataset_base, f"images/{split_type}", os.path.basename(img_path)))
        shutil.copy(txt_path, os.path.join(dataset_base, f"labels/{split_type}", os.path.basename(txt_path)))

copy_files(X_train, "train")
copy_files(X_val, "val")
copy_files(X_test, "test")

print(f"\nDataset successfully built at: {dataset_base}")
print(f" -> Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}")

import yaml
from ultralytics import YOLO

# 1. Create dataset configuration file for the split dataset
split_yaml = {
    'path': '/content/yolo_dataset',
    'train': 'images/train',
    'val': 'images/val',
    'test': 'images/test',
    'names': {
        0: 'Cone', 1: 'Traffic Barrier', 2: 'Cow', 3: 'Pedestrian',
        4: 'Bicyclist', 5: 'Red Traffic Light', 6: 'Green Traffic Light',
        7: 'Orange Traffic Light', 8: 'Two-Wheeler', 9: 'Speed Limit Sign 10',
        10: 'Speed Limit Sign 15', 11: 'Speed Limit Sign 30', 12: 'Cars'
    }
}

with open("/content/split_data.yaml", "w") as f:
    yaml.dump(split_yaml, f)

# 2. Train YOLO model on the stratified split dataset
model = YOLO("yolo11s.pt")
model.train(
    data="/content/split_data.yaml",
    epochs=10,
    imgsz=640,
    batch=16,
    device=0
)

# 3. Save newly trained best model weights to Google Drive
!cp /content/runs/detect/train/weights/best.pt "/content/drive/MyDrive/yolo11s_stratified_best.pt"
print("Stratified model saved to Drive!")

#evaluation of splits Evaluate Metrics on the Unseen Test Set:
from ultralytics import YOLO

# Load your newly trained model from Drive
model = YOLO("/content/drive/MyDrive/yolo11s_stratified_best.pt")

# Evaluate performance specifically on the 'test' split
metrics = model.val(data="/content/split_data.yaml", split="test")

# Print key accuracy scores
print(f"mAP50-95: {metrics.box.map}")
print(f"mAP50:    {metrics.box.map50}")

#Display Performance Summary Charts
from IPython.display import Image, display

# Display overall loss and accuracy graphs across epochs
display(Image(filename='/content/runs/detect/train/results.png'))

import os
import glob
import matplotlib.pyplot as plt
from collections import Counter

def get_split_classes(split_type):
    classes = []
    label_files = glob.glob(f"/content/yolo_dataset/labels/{split_type}/*.txt")
    for lf in label_files:
        try:
            with open(lf, "r") as f:
                for line in f:
                    parts = line.strip().split()
                    if parts:
                        classes.append(int(float(parts[0])))
        except Exception:
            pass
    return classes

y_train = get_split_classes("train")
y_val = get_split_classes("val")
y_test = get_split_classes("test")

all_classes = sorted(list(set(y_train + y_val + y_test)))

plt.figure(figsize=(12, 5))
plt.hist(
    [y_train, y_val, y_test],
    bins=range(min(all_classes), max(all_classes) + 2),
    label=['Train (70%)', 'Val (20%)', 'Test (10%)'],
    align='left'
)
plt.xticks(all_classes, [f"ID {i}" for i in all_classes])
plt.xlabel("Class ID")
plt.ylabel("Number of Object Instances")
plt.title("Dataset Distribution Across Train / Val / Test Splits")
plt.legend()
plt.tight_layout()
plt.savefig("/content/split_distribution.png")
plt.show()

#evaluate your trained model
import glob
from ultralytics import YOLO
from IPython.display import Image, display

# 1. Load your best model weights saved from the split training
model = YOLO("/content/drive/MyDrive/yolo11s_stratified_best.pt")

# 2. Run prediction on the unseen test images split
results = model.predict(source="/content/yolo_dataset/images/test", save=True, conf=0.25)

# 3. Display one of the output predictions with detected bounding boxes
predicted_images = glob.glob("/content/runs/detect/predict*/*.jpg")
if predicted_images:
    display(Image(filename=predicted_images[0]))

import glob
from ultralytics import YOLO
from IPython.display import Image, display

# 1. Load your best trained model directly from Drive
model = YOLO("/content/drive/MyDrive/yolo11s_stratified_best.pt")

# 2. Run prediction on the test set
results = model.predict(source="/content/yolo_dataset/images/test", save=True, conf=0.25)

# 3. Display the first detected image
predicted_images = glob.glob("/content/runs/detect/predict*/*.jpg")
if predicted_images:
    display(Image(filename=predicted_images[0]))

#Mosaic (0.8) and MixUp (0.15) augmentations:
import os
import glob
import shutil
import yaml
from sklearn.model_selection import train_test_split
from ultralytics import YOLO

# 1. Collect all valid image-label pairs across /content
all_images = []
for ext in ("*.jpg", "*.jpeg", "*.png", "*.JPG", "*.JPEG", "*.PNG"):
    all_images.extend(glob.glob("/content/**/" + ext, recursive=True))

all_images = [img for img in all_images if ".ipynb_checkpoints" not in img and "yolo_dataset" not in img]

image_label_pairs = []

for img in all_images:
    txt_path = os.path.splitext(img)[0] + ".txt"
    if not os.path.exists(txt_path):
        alt_txt_path = img.replace("/images/", "/labels/")
        alt_txt_path = os.path.splitext(alt_txt_path)[0] + ".txt"
        if os.path.exists(alt_txt_path):
            txt_path = alt_txt_path

    if os.path.exists(txt_path):
        image_label_pairs.append((img, txt_path))

if not image_label_pairs:
    raise RuntimeError("No image-label pairs found in /content! Check your dataset unzipping.")

# 2. Split dataset into Train (70%), Val (20%), and Test (10%)
X_train_val, X_test = train_test_split(image_label_pairs, test_size=0.10, random_state=42)
X_train, X_val = train_test_split(X_train_val, test_size=0.2222, random_state=42)

dataset_base = "/content/yolo_dataset"
for split in ["train", "val", "test"]:
    os.makedirs(os.path.join(dataset_base, f"images/{split}"), exist_ok=True)
    os.makedirs(os.path.join(dataset_base, f"labels/{split}"), exist_ok=True)

def copy_files(split_data, split_type):
    for img_path, txt_path in split_data:
        shutil.copy(img_path, os.path.join(dataset_base, f"images/{split_type}", os.path.basename(img_path)))
        shutil.copy(txt_path, os.path.join(dataset_base, f"labels/{split_type}", os.path.basename(txt_path)))

copy_files(X_train, "train")
copy_files(X_val, "val")
copy_files(X_test, "test")

# 3. Write data.yaml configuration
class_names = {
    0: "cone", 1: "obstacle", 2: "cow", 3: "pedestrian",
    4: "bicycle", 5: "red_signal", 6: "green_signal", 7: "yellow_signal",
    8: "twowheeler", 9: "sign10", 10: "trafficsign", 11: "sign30", 12: "vehicle"
}

yaml_data = {
    "path": dataset_base,
    "train": "images/train",
    "val": "images/val",
    "test": "images/test",
    "names": class_names,
}

yaml_path = os.path.join(dataset_base, "data.yaml")
with open(yaml_path, "w") as f:
    yaml.dump(yaml_data, f, default_flow_style=False, sort_keys=True)

print("Dataset successfully built and data.yaml created!")

# 4. Train YOLO11s model with Mosaic and MixUp augmentations
model = YOLO("yolo11s.pt")
model.train(
    data=yaml_path,
    epochs=10,
    imgsz=640,
    batch=16,
    mosaic=0.8,
    mixup=0.15,
    workers=8,
    amp=True,
    device=0
)

# 5. Backup trained weights to Google Drive
!cp /content/runs/detect/train/weights/best.pt "/content/drive/MyDrive/yolo11s_augmented_best.pt"
print("Augmented training complete and weights saved to Drive!")

# Verify Detection, Localization, and System Latency/FPS Metrics
import time
import torch
from ultralytics import YOLO

# 1. Load trained model
model_path = "/content/runs/detect/train/weights/best.pt"
model = YOLO(model_path)

print("--- 1. EVALUATING DETECTION & LOCALIZATION METRICS ---")
# Run validation on the split dataset
metrics = model.val(
    data="/content/yolo_dataset/data.yaml",
    split="val",
    imgsz=640,
    iou=0.45,
    device=0 if torch.cuda.is_available() else 'cpu'
)

# Extract Detection Metrics
precision = metrics.box.mp
recall = metrics.box.mr
map50 = metrics.box.map50
map50_95 = metrics.box.map

print("\n[KPI Verification Results]")
print(f" -> Precision (Target >= 0.85):   {precision:.4f} [{'PASS' if precision >= 0.85 else 'FAIL'}]")
print(f" -> Recall (Target >= 0.82):      {recall:.4f} [{'PASS' if recall >= 0.82 else 'FAIL'}]")
print(f" -> mAP@50 (Target >= 0.80):      {map50:.4f} [{'PASS' if map50 >= 0.80 else 'FAIL'}]")
print(f" -> mAP@50-95:                    {map50_95:.4f}")

# 2. MEASURE SYSTEM METRICS (Latency & FPS)
print("\n--- 2. MEASURING SYSTEM METRICS (LATENCY & FPS) ---")
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Set underlying PyTorch model to evaluation mode
model.model.eval()
model.model.to(device)

# Dummy 640x640 frame simulating camera feed
dummy_input = torch.randn(1, 3, 640, 640).to(device)

# Warmup GPU
with torch.no_grad():
    for _ in range(20):
        _ = model.model(dummy_input)

if torch.cuda.is_available():
    torch.cuda.synchronize()

# Benchmark 100 inference passes
start_time = time.time()
num_samples = 100

with torch.no_grad():
    for _ in range(num_samples):
        _ = model.model(dummy_input)

if torch.cuda.is_available():
    torch.cuda.synchronize()

total_time = time.time() - start_time
avg_latency_ms = (total_time / num_samples) * 1000
fps = 1000 / avg_latency_ms

print(f" -> End-to-End Latency (Target < 15ms): {avg_latency_ms:.2f} ms [{'PASS' if avg_latency_ms < 15 else 'FAIL'}]")
print(f" -> Frame Rate (Target >= 60 FPS):      {fps:.2f} FPS [{'PASS' if fps >= 60 else 'FAIL'}]")

#Real-World Failure Case Measurement & Confusion Matrix
from ultralytics import YOLO

# 1. Load trained model
model = YOLO("/content/runs/detect/train/weights/best.pt")

# 2. Generate Confusion Matrix and Failure Analysis on Test Split
metrics = model.val(data="/content/yolo_dataset/data.yaml", split="test", save_json=True)

# 3. Print Class-Wise Failure Cases (Precision & Recall per class)
print("\n--- CLASS-WISE PERFORMANCE & FAILURE CASES ---")
for i, name in enumerate(metrics.names.values()):
    p = metrics.box.p[i] if len(metrics.box.p) > i else 0
    r = metrics.box.r[i] if len(metrics.box.r) > i else 0
    print(f"Class [{name}]: Precision = {p:.3f} | Recall = {r:.3f}")

#ONNX Model Export for Jetson Orin NX Deployment
from ultralytics import YOLO

# Load best trained weights
model = YOLO("/content/runs/detect/train/weights/best.pt")

# Export to ONNX format cleanly
onnx_file = model.export(format="onnx", imgsz=640, dynamic=False, half=True)
print(f"Model exported cleanly to: {onnx_file}")

#Standardized Output Bounding Box Formatter
import torch

def format_detections(results, class_names_map):
    formatted_outputs = []
    for r in results:
        boxes = r.boxes
        for box in boxes:
            # Extract coordinates [x_min, y_min, x_max, y_max]
            xyxy = box.xyxy[0].cpu().numpy().tolist()
            conf = float(box.conf[0].cpu().numpy())
            cls_id = int(box.cls[0].cpu().numpy())
            cls_name = class_names_map.get(cls_id, f"Class_{cls_id}")

            formatted_outputs.append({
                "bbox": [round(c, 2) for c in xyxy],
                "label": cls_name,
                "confidence": round(conf, 4)
            })
    return formatted_outputs

#EXPORT TO DRIVE
import os
import shutil

# Ensure Google Drive directory path exists
drive_folder = "/content/drive/MyDrive/YOLO_Weights"
os.makedirs(drive_folder, exist_ok=True)

# Define source paths
pt_source = "/content/runs/detect/train/weights/best.pt"
onnx_source = "/content/runs/detect/train/weights/best.onnx"

# Copy PyTorch weights
if os.path.exists(pt_source):
    shutil.copy(pt_source, os.path.join(drive_folder, "yolo11s_best.pt"))
    print("✅ Successfully copied best.pt to Google Drive!")
else:
    print("⚠️ Could not find best.pt file.")

# Copy ONNX exported model
if os.path.exists(onnx_source):
    shutil.copy(onnx_source, os.path.join(drive_folder, "yolo11s_best.onnx"))
    print("✅ Successfully copied best.onnx to Google Drive!")
else:
    print("⚠️ Could not find best.onnx file.")

#CHECK IF DONE OR NOT
!ls -lh "/content/drive/MyDrive/YOLO_Weights"

!pip install ultralytics

import yaml

# List of your dataset directories
DATA_FOLDERS = [
    '/content/data_cone', '/content/data_obstacle', '/content/data_cow',
    '/content/data_pedestrian', '/content/data_bicycle', '/content/data_red',
    '/content/data_green', '/content/data_yellow', '/content/data_two_wheeler',
    '/content/data_sign10', '/content/data_traffic_sign', '/content/data_sign30',
    '/content/data_vehicle'
]

# Define 13 unified target classes
yaml_content = {
    'train': DATA_FOLDERS,
    'val': DATA_FOLDERS,
    'nc': 13,
    'names': [
        'Cone', 'Obstacle', 'Cow', 'Pedestrian', 'Bicycle',
        'Red Light', 'Green Light', 'Yellow Light', 'Two-Wheeler',
        'Sign 10', 'Traffic Sign', 'Sign 30', 'Vehicle'
    ]
}

# Save configuration to /content/combined_data.yaml
with open('/content/combined_data.yaml', 'w') as f:
    yaml.dump(yaml_content, f)

print("✅ /content/combined_data.yaml created successfully!")

import os
import yaml
import matplotlib.pyplot as plt
from PIL import Image
from ultralytics import YOLO

# 1. UNZIP DATASETS FROM DRIVE
!mkdir -p ./data_two_wheeler && unzip -o -q "/content/drive/MyDrive/Two Wheeler.zip" -d ./data_two_wheeler
!mkdir -p ./data_vehicle && unzip -o -q "/content/drive/MyDrive/Vehicle.zip" -d ./data_vehicle
!mkdir -p ./data_bicycle && unzip -o -q "/content/drive/MyDrive/bicycle.zip" -d ./data_bicycle
!mkdir -p ./data_cone && unzip -o -q "/content/drive/MyDrive/cone.zip" -d ./data_cone
!mkdir -p ./data_cow && unzip -o -q "/content/drive/MyDrive/cow.zip" -d ./data_cow
!mkdir -p ./data_green && unzip -o -q "/content/drive/MyDrive/green.zip" -d ./data_green
!mkdir -p ./data_obstacle && unzip -o -q "/content/drive/MyDrive/obstacle.zip" -d ./data_obstacle
!mkdir -p ./data_pedestrian && unzip -o -q "/content/drive/MyDrive/pedestrain det.zip" -d ./data_pedestrian
!mkdir -p ./data_red && unzip -o -q "/content/drive/MyDrive/red light.zip" -d ./data_red
!mkdir -p ./data_sign10 && unzip -o -q "/content/drive/MyDrive/sign10.zip" -d ./data_sign10
!mkdir -p ./data_sign30 && unzip -o -q "/content/drive/MyDrive/sign30.zip" -d ./data_sign30
!mkdir -p ./data_traffic_sign && unzip -o -q "/content/drive/MyDrive/traffic sign.zip" -d ./data_traffic_sign
!mkdir -p ./data_yellow && unzip -o -q "/content/drive/MyDrive/yellow.zip" -d ./data_yellow

print("✅ All datasets unzipped successfully!")

# 2. CREATE COMBINED YAML FILE
DATA_FOLDERS = [
    '/content/data_cone', '/content/data_obstacle', '/content/data_cow',
    '/content/data_pedestrian', '/content/data_bicycle', '/content/data_red',
    '/content/data_green', '/content/data_yellow', '/content/data_two_wheeler',
    '/content/data_sign10', '/content/data_traffic_sign', '/content/data_sign30',
    '/content/data_vehicle'
]

yaml_content = {
    'train': DATA_FOLDERS,
    'val': DATA_FOLDERS,
    'nc': 13,
    'names': [
        'Cone', 'Obstacle', 'Cow', 'Pedestrian', 'Bicycle',
        'Red Light', 'Green Light', 'Yellow Light', 'Two-Wheeler',
        'Sign 10', 'Traffic Sign', 'Sign 30', 'Vehicle'
    ]
}

with open('/content/combined_data.yaml', 'w') as f:
    yaml.dump(yaml_content, f)

print("✅ combined_data.yaml created!")

# 3. TRAIN YOLO MODEL
model = YOLO('yolo11s.pt')
results = model.train(
    data='/content/combined_data.yaml',
    epochs=10,
    imgsz=640,
    project='/content/drive/MyDrive/yolo_results',
    name='train_run',
    plots=True
)

# 4. DISPLAY CONFUSION MATRIX & VISUALIZATIONS
SAVE_DIR = results.save_dir

def show_plot(file_name, title):
    path = os.path.join(SAVE_DIR, file_name)
    if os.path.exists(path):
        img = Image.open(path)
        plt.figure(figsize=(10, 10))
        plt.imshow(img)
        plt.axis('off')
        plt.title(title, fontsize=14)
        plt.show()
    else:
        print(f"File not found: {path}")

print("\n--- CONFUSION MATRICES ---")
show_plot('confusion_matrix.png', 'Standard Confusion Matrix')
show_plot('confusion_matrix_normalized.png', 'Normalized Confusion Matrix')

print("\n--- PERFORMANCE METRICS ---")
show_plot('PR_curve.png', 'Precision-Recall Curve')
show_plot('F1_curve.png', 'F1-Score Curve')
show_plot('results.png', 'Training Loss & Metrics Summary')

from ultralytics import YOLO
import glob
import os

# Load the base YOLO model weights
model = YOLO("yolo11s.pt")

# Collect images from light-related folders
light_folders = ["./data_red", "./data_green", "./data_yellow"]
image_paths = []
for folder in light_folders:
    image_paths.extend(glob.glob(os.path.join(folder, "**/*.jpg"), recursive=True))

# Run prediction on light images
if image_paths:
    results = model.predict(source=image_paths[:8], imgsz=640, conf=0.25, save=True)

    # Display the results
    for result in results:
        result.show()
else:
    print("No images found in the specified light folders.")

#proper train/validation split logic to fix data leakage and prevent corrupted labels:
import os
import glob
import random
import yaml

DATA_FOLDERS = [
    "./data_cone", "./data_obstacle", "./data_cow",
    "./data_pedestrian", "./data_bicycle", "./data_red",
    "./data_green", "./data_yellow", "./data_two_wheeler",
    "./data_sign10", "./data_traffic", "./data_sign30",
    "./data_vehicle"
]

FOLDER_CLASS_MAP = {
    "./data_cone": 0, "./data_obstacle": 1, "./data_cow": 2,
    "./data_pedestrian": 3, "./data_bicycle": 4, "./data_red": 5,
    "./data_green": 6, "./data_yellow": 7, "./data_two_wheeler": 8,
    "./data_sign10": 9, "./data_traffic": 10, "./data_sign30": 11,
    "./data_vehicle": 12
}

CLASS_NAMES = {
    0: 'Cone', 1: 'Traffic Barrier', 2: 'Cow', 3: 'Pedestrian',
    4: 'Bicyclist', 5: 'Red Traffic Light', 6: 'Green Traffic Light',
    7: 'Orange Traffic Light', 8: 'Two-Wheeler', 9: 'Speed Limit Sign 10',
    10: 'Speed Limit Sign 15', 11: 'Speed Limit Sign 30', 12: 'Cars'
}

# 1. Map labels safely without corrupting multi-line annotations
for folder, target_id in FOLDER_CLASS_MAP.items():
    txt_files = glob.glob(os.path.join(folder, "**/*.txt"), recursive=True)
    for path in txt_files:
        if "data.yaml" in path or "README" in path:
            continue
        with open(path, "r") as f:
            lines = f.readlines()

        new_lines = []
        for line in lines:
            parts = line.strip().split()
            if len(parts) >= 5:  # Valid YOLO detection line
                parts[0] = str(target_id)
                new_lines.append(" ".join(parts[:5]))  # Retain standard box coordinates only

        with open(path, "w") as f:
            f.write("\n".join(new_lines) + "\n")

# 2. Collect image paths and split into Train (80%) and Validation (20%)
all_images = []
for folder in DATA_FOLDERS:
    for ext in ("*.jpg", "*.jpeg", "*.png"):
        all_images.extend(glob.glob(os.path.join(folder, f"**/{ext}"), recursive=True))

random.seed(42)
random.shuffle(all_images)

split_idx = int(len(all_images) * 0.8)
train_images = all_images[:split_idx]
val_images = all_images[split_idx:]

# Save split image paths to txt files for Ultralytics parser
with open("train_split.txt", "w") as f:
    f.write("\n".join(train_images))

with open("val_split.txt", "w") as f:
    f.write("\n".join(val_images))

# 3. Build data config pointing to explicit train/val text splits
yaml_content = {
    'path': '/content',
    'train': 'train_split.txt',
    'val': 'val_split.txt',
    'names': CLASS_NAMES
}

with open("combined_data.yaml", "w") as f:
    yaml.dump(yaml_content, f)

print(f"Dataset split complete: {len(train_images)} training images, {len(val_images)} validation images.")

#Dataset Preprocessing & YOLO YAML Generation
import os
import shutil
import random
from pathlib import Path

# 1. Setup Dataset Directory Hierarchy
base_dir = Path("./processed_dataset")
train_img_dir = base_dir / "images/train"
val_img_dir = base_dir / "images/val"
train_lbl_dir = base_dir / "labels/train"
val_lbl_dir = base_dir / "labels/val"

for d in [train_img_dir, val_img_dir, train_lbl_dir, val_lbl_dir]:
    d.mkdir(parents=True, exist_ok=True)

# 2. Define Dataset Sources and Explicit Class Remapping
# Update this dict to map dataset folders to their corresponding class IDs
source_folders = {
    "./data_vehicle": 0,
    "./data_pedestrian": 1,
    "./data_cyclist": 2
}

split_ratio = 0.8  # 80% train, 20% validation

for folder_path, target_class_id in source_folders.items():
    folder = Path(folder_path)
    if not folder.exists():
        continue

    # Collect matching image-label pairs
    image_files = [f for f in folder.glob("*.*") if f.suffix.lower() in [".jpg", ".jpeg", ".png"]]
    random.shuffle(image_files)

    split_idx = int(len(image_files) * split_ratio)

    for idx, img_path in enumerate(image_files):
        label_path = img_path.with_suffix(".txt")
        if not label_path.exists():
            continue

        # Determine train or validation split
        if idx < split_idx:
            dest_img = train_img_dir / img_path.name
            dest_lbl = train_lbl_dir / label_path.name
        else:
            dest_img = val_img_dir / img_path.name
            dest_lbl = val_lbl_dir / label_path.name

        # Copy image file
        shutil.copy(img_path, dest_img)

        # Process and clean label lines
        valid_lines = []
        with open(label_path, "r") as f:
            lines = f.readlines()

        for line in lines:
            parts = line.strip().split()
            # Ensure line strictly has 5 elements (class_id, x, y, w, h)
            if len(parts) == 5:
                # Assign the target class ID or process preserving multi-class IDs
                parts[0] = str(target_class_id)
                valid_lines.append(" ".join(parts))

        # Write cleaned annotations
        with open(dest_lbl, "w") as f:
            f.write("\n".join(valid_lines) + ("\n" if valid_lines else ""))

# 3. Create Dataset Configuration YAML
data_yaml_content = f"""
path: {base_dir.resolve()}
train: images/train
val: images/val

names:
  0: vehicle
  1: pedestrian
  2: cyclist
"""

yaml_path = base_dir / "data.yaml"
with open(yaml_path, "w") as f:
    f.write(data_yaml_content.strip())

print(f"Dataset prepared successfully at {base_dir.resolve()}")



import glob
import os
from google.colab import files
from ultralytics import YOLO

# Load model and run prediction
model = YOLO("yolo11s.pt")

light_folders = ["./data_red", "./data_green", "./data_yellow"]
image_paths = []
for folder in light_folders:
    image_paths.extend(glob.glob(os.path.join(folder, "**/*.jpg"), recursive=True))

if image_paths:
    # Run prediction and save to a fixed project folder name
    results = model.predict(
        source=image_paths[:20],
        conf=0.25,
        save=True,
        project="/content/my_predictions",
        name="light_results",
        exist_ok=True
    )

    # Zip and download
    !zip -r /content/light_predictions.zip /content/my_predictions/light_results
    files.download('/content/light_predictions.zip')